emoji_prefix:
  default: ""
  type: enum
  description:
    en: "The prefix for your custom emoji."
width:
  default: "auto"
  description:
    en: "Width for your custom emoji."
height:
  default: "auto"
  description:
    en: "Height for your custom emoji."

